### ISSUE TITLE
Single character literals do not work

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/NQL#20]
Originally reported at https://github.com/TryGhost/GQL/issues/24 & https://github.com/TryGhost/Ghost/issues/8433

--- 

To reproduce:

- On a local blog...
- Create a post with the title A, the slug will be `a`. Publish the post.
- Create a post with the title AB, the slug will be `ab`. Publish the post.
- Visit the frontend of the blog to grab the client secret.
- Open postman
- Try doing a get request for `http://localhost:2368/ghost/api/v0.1/posts?client_id=ghost-frontend&client_secret=[client-secret]&filter=slug:ab` - see that it works
- Try doing a get request for `http://localhost:2368/ghost/api/v0.1/posts?client_id=ghost-frontend&client_secret=[client-secret]&filter=slug:a` - see that it doesn't work

I believe this is due to the plus sign here: https://github.com/TryGhost/GQL/blob/master/src/gql.l#L22

The badcharsincnot regex matches a single character, and then the second group matches a second character. Therefore there must be at least 2 chars for a match.

Fixing this may have other implications, if so, we should close this issue and instead, add a rule that literals must be at least 2 characters to the documentation, provide tests to demo this limitation + if possible, improve the error message.

**Comment by 9larsons** [comment]
Fixed by 07cc8c1.
